//! `musubicad export <assembly> robot.urdf`: URDF robot description (ADR-028).
//!
//! The description is generated from the Design Graph, never edited by hand:
//! links are assembly instances, joints come from the kinematic tree derived
//! from mates, visuals and collisions are regenerated part meshes, and
//! inertials are computed by the geometry kernel.  Change a part parameter and
//! export again; the URDF follows.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use opencad_assembly::{kinematic_tree, JointKind, KinematicLink};
use opencad_core::{DocumentKind, OpenCadError, Result};
use opencad_feature::FeatureRegistry;
use opencad_file::read_ocad;
use opencad_geometry::{write_binary_stl, GeometryKernel, RigidTransform, TessellationSettings};
use opencad_kernel_occt::OcctGeometryKernel;

use crate::export::ExportSummary;
use crate::regen::{assembly_root, DEFAULT_DENSITY_KG_PER_M3};

/// Mass and mesh of one component, in its part frame.
struct ComponentBody {
    mesh_file: String,
    triangles: usize,
    mass_kg: f64,
    center_of_mass_m: [f64; 3],
    inertia_kg_m2: [[f64; 3]; 3],
}

/// Write `output` (a `.urdf`) and one binary STL per component next to it.
pub fn export_urdf(input: &str, output: &str) -> Result<ExportSummary> {
    let doc = read_ocad(input)?;
    let assembly = doc.assembly.as_ref().ok_or_else(|| {
        OpenCadError::validation("URDF export needs an assembly document with mated instances")
    })?;
    let tree = kinematic_tree(assembly)?;
    let robot = short_name(doc.metadata.id.as_str());
    let output_path = Path::new(output);
    let directory = output_path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    fs::create_dir_all(&directory)
        .map_err(|error| OpenCadError::Other(format!("cannot create output directory: {error}")))?;

    let root = assembly_root(input);
    let kernel = OcctGeometryKernel::new();
    let mut bodies: BTreeMap<String, ComponentBody> = BTreeMap::new();
    for link in &tree.links {
        let instance = assembly
            .instances
            .iter()
            .find(|instance| instance.id == link.instance)
            .ok_or_else(|| {
                OpenCadError::validation(format!("instance '{}' not found", link.instance))
            })?;
        let component_id = instance.component.as_str().to_string();
        if bodies.contains_key(&component_id) {
            continue;
        }
        let component = assembly.component(&instance.component).ok_or_else(|| {
            OpenCadError::validation(format!("component '{}' not found", instance.component))
        })?;
        let mesh_file = format!("{robot}_{}.stl", short_name(&component_id));
        let body = component_body(
            &kernel,
            &root.join(&component.source_path),
            &directory.join(&mesh_file),
            mesh_file,
        )
        .map_err(|error| error.with_context(format!("component '{component_id}'")))?;
        bodies.insert(component_id, body);
    }

    let mut xml = String::new();
    let _ = writeln!(xml, "<?xml version=\"1.0\"?>");
    let _ = writeln!(
        xml,
        "<!-- Generated by musubicad from {} ({}). Edit the Design Graph, not this file.",
        xml_escape(doc.metadata.id.as_str()),
        xml_escape(&doc.metadata.name)
    );
    let _ = writeln!(
        xml,
        "     Joint zero positions are the assembly's current pose; density {DEFAULT_DENSITY_KG_PER_M3} kg/m^3. -->"
    );
    let _ = writeln!(xml, "<robot name=\"{}\">", xml_escape(&robot));
    let mut triangles = 0;
    for link in &tree.links {
        let instance = assembly
            .instances
            .iter()
            .find(|instance| instance.id == link.instance)
            .ok_or_else(|| {
                OpenCadError::validation(format!("instance '{}' not found", link.instance))
            })?;
        let body = &bodies[instance.component.as_str()];
        triangles += body.triangles;
        write_link(&mut xml, link, body);
    }
    for link in &tree.links {
        write_joint(&mut xml, link);
    }
    let _ = writeln!(xml, "</robot>");
    fs::write(output_path, &xml)
        .map_err(|error| OpenCadError::Other(format!("cannot write '{output}': {error}")))?;

    Ok(ExportSummary {
        format: "urdf".into(),
        triangles,
        output: output.to_string(),
        bytes: Some(xml.len()),
    })
}

fn component_body(
    kernel: &OcctGeometryKernel,
    source: &Path,
    mesh_path: &Path,
    mesh_file: String,
) -> Result<ComponentBody> {
    let doc = read_ocad(source)?;
    if doc.metadata.kind != DocumentKind::Part {
        return Err(OpenCadError::validation(
            "URDF export supports part components only; flatten nested assemblies first",
        ));
    }
    let parameters = doc.parameters.clone();
    let refs = doc.semantic_refs.clone();
    let mut model = doc.into_part_model();
    model.regenerate(
        kernel,
        &FeatureRegistry::with_defaults(),
        Some(&parameters),
        Some(&refs),
    )?;
    let body = model
        .active_body()
        .ok_or_else(|| OpenCadError::validation("part has no solid body"))?;
    let mass = kernel.mass_properties(body, DEFAULT_DENSITY_KG_PER_M3)?;
    let inertia = kernel.inertia_about_com(body, DEFAULT_DENSITY_KG_PER_M3)?;
    let mesh = kernel.tessellate(body, &TessellationSettings::default())?;
    write_binary_stl(mesh_path, &mesh, &mesh_file)?;
    Ok(ComponentBody {
        mesh_file,
        triangles: mesh.triangle_count(),
        mass_kg: mass.mass_kg,
        center_of_mass_m: mass.center_of_mass,
        inertia_kg_m2: inertia,
    })
}

fn write_link(xml: &mut String, link: &KinematicLink, body: &ComponentBody) {
    // The link frame is the part frame shifted to `frame_in_part`, so part
    // coordinates move into the link by subtracting that offset.
    let offset = link.frame_in_part.translation_m;
    let shift = |point: [f64; 3]| {
        [
            point[0] - offset[0],
            point[1] - offset[1],
            point[2] - offset[2],
        ]
    };
    let name = short_name(link.instance.as_str());
    let tensor = body.inertia_kg_m2;
    let tolerance = SNAP_INERTIA_RELATIVE * (tensor[0][0] + tensor[1][1] + tensor[2][2]).abs();
    let inertia = tensor.map(|row| row.map(|value| snap(value, tolerance)));
    let _ = writeln!(xml, "  <link name=\"{}\">", xml_escape(&name));
    let _ = writeln!(xml, "    <inertial>");
    let _ = writeln!(
        xml,
        "      <origin xyz=\"{}\" rpy=\"0 0 0\"/>",
        vector(shift(body.center_of_mass_m))
    );
    let _ = writeln!(xml, "      <mass value=\"{}\"/>", number(body.mass_kg));
    let _ = writeln!(
        xml,
        "      <inertia ixx=\"{}\" ixy=\"{}\" ixz=\"{}\" iyy=\"{}\" iyz=\"{}\" izz=\"{}\"/>",
        number(inertia[0][0]),
        number(inertia[0][1]),
        number(inertia[0][2]),
        number(inertia[1][1]),
        number(inertia[1][2]),
        number(inertia[2][2])
    );
    let _ = writeln!(xml, "    </inertial>");
    for element in ["visual", "collision"] {
        let _ = writeln!(xml, "    <{element}>");
        let _ = writeln!(
            xml,
            "      <origin xyz=\"{}\" rpy=\"0 0 0\"/>",
            vector(shift([0.0; 3]))
        );
        let _ = writeln!(
            xml,
            "      <geometry><mesh filename=\"{}\"/></geometry>",
            xml_escape(&body.mesh_file)
        );
        let _ = writeln!(xml, "    </{element}>");
    }
    let _ = writeln!(xml, "  </link>");
}

fn write_joint(xml: &mut String, link: &KinematicLink) {
    let Some(joint) = &link.joint else {
        return;
    };
    let child = short_name(link.instance.as_str());
    let name = joint
        .mate
        .as_ref()
        .map(|mate| short_name(mate.as_str()))
        .unwrap_or_else(|| format!("{child}_fixed"));
    let kind = match joint.kind {
        JointKind::Continuous { .. } => "continuous",
        JointKind::Revolute { .. } => "revolute",
        JointKind::Prismatic { .. } => "prismatic",
        JointKind::Fixed => "fixed",
    };
    let _ = writeln!(
        xml,
        "  <joint name=\"{}\" type=\"{kind}\">",
        xml_escape(&name)
    );
    let _ = writeln!(
        xml,
        "    <parent link=\"{}\"/>",
        xml_escape(&short_name(joint.parent.as_str()))
    );
    let _ = writeln!(xml, "    <child link=\"{}\"/>", xml_escape(&child));
    let _ = writeln!(
        xml,
        "    <origin xyz=\"{}\" rpy=\"{}\"/>",
        vector(joint.origin.translation_m),
        vector(roll_pitch_yaw(&joint.origin))
    );
    match joint.kind {
        JointKind::Continuous { axis } => {
            let _ = writeln!(xml, "    <axis xyz=\"{}\"/>", vector(axis));
        }
        JointKind::Revolute {
            axis,
            lower,
            upper,
            effort,
            velocity,
        }
        | JointKind::Prismatic {
            axis,
            lower,
            upper,
            effort,
            velocity,
        } => {
            let _ = writeln!(xml, "    <axis xyz=\"{}\"/>", vector(axis));
            let _ = writeln!(
                xml,
                "    <limit lower=\"{}\" upper=\"{}\" effort=\"{}\" velocity=\"{}\"/>",
                number(lower),
                number(upper),
                number(effort),
                number(velocity)
            );
        }
        JointKind::Fixed => {}
    }
    let _ = writeln!(xml, "  </joint>");
}

/// URDF fixed-axis roll, pitch, yaw (R = Rz(yaw) · Ry(pitch) · Rx(roll)).
fn roll_pitch_yaw(transform: &RigidTransform) -> [f64; 3] {
    let r = transform.rotation;
    let roll = r[2][1].atan2(r[2][2]);
    let pitch = (-r[2][0]).atan2((r[2][1] * r[2][1] + r[2][2] * r[2][2]).sqrt());
    let yaw = r[1][0].atan2(r[0][0]);
    [roll, pitch, yaw]
}

/// `instance:upper_arm` -> `upper_arm`.
fn short_name(id: &str) -> String {
    id.rsplit(':').next().unwrap_or(id).to_string()
}

/// Lengths and angles below this are kernel noise (0.001 nm, 1e-12 rad).
const SNAP_ABSOLUTE: f64 = 1e-12;
/// Inertia products below this fraction of the tensor's trace are noise.
const SNAP_INERTIA_RELATIVE: f64 = 1e-9;

fn snap(value: f64, tolerance: f64) -> f64 {
    if value.abs() < tolerance {
        0.0
    } else {
        value
    }
}

/// Deterministic number text: 12 significant digits, scientific notation
/// below 1e-4, no negative zero.
fn number(value: f64) -> String {
    let rounded = crate::diff::round_significant(value);
    if rounded == 0.0 {
        "0".into()
    } else if rounded.abs() < 1e-4 {
        format!("{rounded:e}")
    } else {
        format!("{rounded}")
    }
}

/// Length or angle triple with kernel noise removed.
fn vector(value: [f64; 3]) -> String {
    format!(
        "{} {} {}",
        number(snap(value[0], SNAP_ABSOLUTE)),
        number(snap(value[1], SNAP_ABSOLUTE)),
        number(snap(value[2], SNAP_ABSOLUTE))
    )
}

fn xml_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roll_pitch_yaw_recovers_a_yaw_rotation() {
        let angle = -std::f64::consts::FRAC_PI_4;
        let (s, c) = angle.sin_cos();
        let transform = RigidTransform {
            translation_m: [0.0; 3],
            rotation: [[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]],
        };
        let [roll, pitch, yaw] = roll_pitch_yaw(&transform);
        assert!(roll.abs() < 1e-12 && pitch.abs() < 1e-12);
        assert!((yaw - angle).abs() < 1e-12);
    }

    #[test]
    fn numbers_are_deterministic_and_never_negative_zero() {
        assert_eq!(number(-0.0), "0");
        assert_eq!(number(0.16000000000000003), "0.16");
        assert_eq!(vector([1.0, -2.5, 0.0]), "1 -2.5 0");
        assert_eq!(vector([1.4e-17, -4e-21, 0.11]), "0 0 0.11");
        assert_eq!(number(7.37686166402e-6), "7.37686166402e-6");
    }

    #[test]
    fn robot_arm_exports_links_joints_meshes_and_inertials() {
        let dir = tempfile::tempdir().expect("tempdir");
        let output = dir.path().join("arm").join("robot_arm.urdf");
        let input = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../examples/robot_arm_assembly.ocad.d"
        );
        let summary = export_urdf(input, output.to_str().expect("path")).expect("export");
        assert_eq!(summary.format, "urdf");
        assert!(summary.triangles > 0);
        let xml = fs::read_to_string(&output).expect("urdf");

        assert_eq!(xml.matches("<link name=").count(), 4);
        assert_eq!(xml.matches("type=\"revolute\"").count(), 3);
        // Elbow limits from the Design Graph: -100° to +140°, 1 N·m, 3 rad/s.
        assert!(
            xml.contains("<limit lower=\"-1.74532925199\" upper=\"2.44346095279\" effort=\"1\" velocity=\"3\"/>"),
            "{xml}"
        );
        for joint in ["shoulder", "elbow", "wrist"] {
            assert!(xml.contains(&format!("<joint name=\"{joint}\"")), "{joint}");
        }
        assert!(xml.contains("<parent link=\"upper_arm\"/>\n    <child link=\"forearm\"/>"));
        // Elbow: 160 mm along the upper arm and 14 mm up, at the -45° pose.
        assert!(
            xml.contains("<origin xyz=\"0 0.16 0.014\" rpy=\"0 0 -0.785398163397\"/>"),
            "{xml}"
        );
        for component in ["base", "upper_arm", "forearm", "gripper"] {
            let mesh = dir
                .path()
                .join("arm")
                .join(format!("robot_arm_assembly_001_{component}.stl"));
            assert!(fs::metadata(&mesh).expect("mesh").len() > 84, "{component}");
        }

        // Masses match the assembly's regenerated total.
        let masses: f64 = xml
            .lines()
            .filter_map(|line| line.trim().strip_prefix("<mass value=\""))
            .map(|rest| rest.trim_end_matches("\"/>").parse::<f64>().expect("mass"))
            .sum();
        let summary = crate::regen::regen_document(input, false).expect("regen");
        let total = summary.mass_kg.expect("assembly mass");
        assert!(
            (masses - total).abs() < 1e-9 * total.max(1.0),
            "{masses} vs {total}"
        );

        // Every inertia is physically valid: positive moments, triangle inequality.
        for line in xml
            .lines()
            .filter(|line| line.trim().starts_with("<inertia "))
        {
            let value = |key: &str| -> f64 {
                let start = line.find(&format!("{key}=\"")).expect(key) + key.len() + 2;
                line[start..]
                    .split('"')
                    .next()
                    .expect("value")
                    .parse()
                    .expect("number")
            };
            let (ixx, iyy, izz) = (value("ixx"), value("iyy"), value("izz"));
            assert!(ixx > 0.0 && iyy > 0.0 && izz > 0.0, "{line}");
            let slack = 1e-12;
            assert!(
                ixx + iyy + slack >= izz && iyy + izz + slack >= ixx && izz + ixx + slack >= iyy
            );
        }

        // Deterministic: a second export is byte-identical.
        let again = dir.path().join("again").join("robot_arm.urdf");
        export_urdf(input, again.to_str().expect("path")).expect("export again");
        assert_eq!(xml, fs::read_to_string(again).expect("urdf"));
    }
}
