"""Render docs/assets/agent-demo/hero.gif, the README's opening animation.

The left side abridges docs/assets/agent-demo/hero-session.json, a real
Claude Code session with the MusubiCAD plugin. Every quoted fact is checked
against that transcript before anything is drawn.

The right side shows only real output:

- the actuator housing regenerated by `musubicad` at evenly spaced values
  between the old and new hub size (each step is applied with `musubicad
  patch`, so each one is verified before it is rendered with `musubicad
  preview`);
- `hero-preview.png`, the exact PNG the agent looked at, which must match
  the last regenerated step pixel for pixel;
- the URDF the agent exported, loaded in MuJoCo (frames from
  `render-urdf-mujoco.py`).

    musubicad export examples/robot_arm_assembly.ocad.d /tmp/arm/robot_arm.urdf
    MUJOCO_GL=osmesa python docs/assets/render-urdf-mujoco.py \
        /tmp/arm/robot_arm.urdf /tmp/arm/arm.gif
    python docs/assets/generate-hero-demo.py --arm-gif /tmp/arm/arm.gif

Needs Pillow and the `musubicad` binary (`--musubicad PATH` if it is not on
PATH).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import tempfile
import textwrap
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFont, ImageSequence

ASSETS = Path(__file__).resolve().parent
REPO = ASSETS.parent.parent
SESSION = ASSETS / "agent-demo" / "hero-session.json"
AGENT_PREVIEW = ASSETS / "agent-demo" / "hero-preview.png"
OUTPUT = ASSETS / "agent-demo" / "hero.gif"
MARK = ASSETS / "musubicad-mark.png"
ACTUATOR = REPO / "examples" / "robot_joint_actuator.ocad.d"
MONO = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
MONO_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
SANS_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
SANS = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

WIDTH, HEIGHT = 1200, 675
LEFT_X, LEFT_W, TOP = 30, 520, 74
PANEL = (580, 92, 600, 450)  # x, y, w, h of the picture
BACKGROUND = (17, 23, 34)
COLORS = {
    "user": (109, 213, 255),
    "tool": (154, 163, 178),
    "ok": (94, 214, 141),
    "bad": (255, 120, 112),
    "text": (231, 237, 247),
    "dim": (120, 130, 148),
}
HUB_FROM, HUB_TO, STEPS = (52.0, 32.0), (64.0, 48.0), 8

# Each scene: lines (kind, text, facts that must appear in the transcript).
# A line may carry a picture cue: "morph", "agent", "refused", "arm".
SCENES = [
    [
        ("user", "> In actuator.ocad.d, make the upper hub 64 mm in diameter and 48 mm tall. Check the change before you apply it, then apply it and take a look at the part.", ["make the upper hub 64 mm in diameter and 48 mm tall"], "start"),
        ("tool", "  musubicad · patch_dry_run", ['"tool": "patch_dry_run"'], None),
        ("ok", "  ✓ verified: rebuilds, expected effects hold", ['"passed": true'], None),
        ("text", "upper hub  52 mm → 64 mm Ø, 32 → 48 mm tall", ['"before": "52 mm"', '"after": "64 mm"', '"before": "32 mm"', '"after": "48 mm"'], None),
        ("text", "mass       609.23 g → 764.09 g (+154.9 g)", ["609.23 g → 764.09 g (+154.9 g)"], None),
        ("tool", "  musubicad · patch_apply", ['"tool": "patch_apply"'], "morph"),
        ("tool", "  musubicad · preview_document", ['"tool": "preview_document"'], "agent"),
        ("text", "The six radial reinforcement ribs can't be seen in the picture.", ["The six radial reinforcement ribs can't be seen in the picture."], None),
    ],
    [
        ("user", "> Now make the shaft bore 100 mm.", ["Now make the shaft bore 100 mm."], "agent"),
        ("tool", "  musubicad · patch_dry_run", ['"tool": "patch_dry_run"'], None),
        ("bad", "  ✗ feature 'feature:radial_ribs': got 2 solids", ["feature 'feature:radial_ribs'", "got 2"], "refused"),
        ("text", "I didn't apply this. … nothing was written.", ["I didn't apply this.", "nothing was written."], None),
    ],
    [
        ("user", "> Leave it as it is. Export robot_arm.ocad.d to urdf/robot_arm.urdf so I can load it in MuJoCo.", ["Export robot_arm.ocad.d to urdf/robot_arm.urdf"], None),
        ("tool", "  musubicad · export_document", ['"tool": "export_document"'], None),
        ("ok", "  ✓ urdf/robot_arm.urdf + one STL per part", ['"output": "urdf/robot_arm.urdf"', "robot_arm_assembly_001_base.stl"], "arm"),
        ("text", "shoulder ±150°\nelbow    −100° to +140°\nwrist    ±90°", ["| shoulder | ±150° |", "| elbow | −100° to +140° |", "| wrist | ±90° |"], None),
    ],
]
CHAPTERS = ["1  Edit + verify", "2  Bad edit refused", "3  Export to a simulator"]
CAPTIONS = {
    "start": "actuator.ocad.d before the change",
    "morph": "regenerated by musubicad: hub 52 → 64 mm Ø, 32 → 48 mm",
    "agent": "preview_document: the PNG the agent looked at",
    "refused": "refused: the file still holds the 64 mm hub",
    "arm": "the exported URDF in MuJoCo 3.15 (loaded after the session)",
}


def font(path: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(path, size)


def verify_facts(transcript: str) -> None:
    missing = [f for scene in SCENES for _, _, facts, _ in scene for f in facts if f not in transcript]
    if missing:
        raise SystemExit(f"facts not found in {SESSION.name}: {missing}")


def run(cmd: list[str]) -> str:
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def regenerate_hub_steps(musubicad: str, work: Path) -> list[Image.Image]:
    """Apply and render the hub change in STEPS verified patches."""
    frames = []
    for i in range(STEPS + 1):
        doc = work / f"step{i}.ocad.d"
        shutil.copytree(ACTUATOR, doc)
        t = i / STEPS
        diameter = HUB_FROM[0] + (HUB_TO[0] - HUB_FROM[0]) * t
        height = HUB_FROM[1] + (HUB_TO[1] - HUB_FROM[1]) * t
        patch = work / f"step{i}.json"
        patch.write_text(json.dumps({
            "intent": f"Hub step {i}",
            "operations": [
                {"type": "set_parameter", "id": "param:upper_hub_diameter", "expr": f"{diameter:g} mm"},
                {"type": "set_parameter", "id": "param:upper_hub_height", "expr": f"{height:g} mm"},
            ],
        }))
        if i:
            run([musubicad, "patch", str(doc), str(patch)])
        png = work / f"step{i}.png"
        run([musubicad, "preview", str(doc), str(png), "--view", "iso", "--width", "640", "--height", "480"])
        frames.append(Image.open(png).convert("RGB"))
    agent = Image.open(AGENT_PREVIEW).convert("RGB")
    if ImageChops.difference(frames[-1], agent).getbbox() is not None:
        raise SystemExit("the final regenerated step does not match the PNG the agent saw")
    frames[-1] = agent
    return frames


def fit(image: Image.Image, box: tuple[int, int, int, int] | None = None) -> Image.Image:
    _, _, w, h = PANEL
    image = image.convert("RGB")
    if box is not None:
        image = image.crop(box)
    return image.resize((w, h), Image.LANCZOS)


def shared_crop(images: list[Image.Image], margin: int = 24) -> tuple[int, int, int, int]:
    """One 4:3 box around the part in every image, so zooming never jumps."""
    left, top, right, bottom = images[0].width, images[0].height, 0, 0
    for image in images:
        background = Image.new("RGB", image.size, image.getpixel((0, 0)))
        bbox = ImageChops.difference(image, background).getbbox()
        if bbox:
            left, top = min(left, bbox[0]), min(top, bbox[1])
            right, bottom = max(right, bbox[2]), max(bottom, bbox[3])
    left, top, right, bottom = left - margin, top - margin, right + margin, bottom + margin
    width, height = right - left, bottom - top
    if width * 3 > height * 4:
        grow = width * 3 // 4 - height
        top, bottom = top - grow // 2, bottom + grow - grow // 2
    else:
        grow = height * 4 // 3 - width
        left, right = left - grow // 2, right + grow - grow // 2
    return left, top, right, bottom


def wrap(text: str, width: int) -> list[str]:
    indent = "  " if text.startswith("> ") else ""
    rows: list[str] = []
    for part in text.split("\n"):
        rows += textwrap.wrap(part, width=width, subsequent_indent=indent) or [""]
    return rows


class Canvas:
    def __init__(self) -> None:
        self.mono = font(MONO, 17)
        self.small = font(SANS, 15)
        self.header = font(MONO_BOLD, 15)
        self.frames: list[Image.Image] = []
        self.durations: list[int] = []

    def base(self, lines: list[tuple[str, str]], picture: Image.Image | None, caption: str, refused: bool, chapter: int) -> Image.Image:
        img = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
        d = ImageDraw.Draw(img)
        d.text((LEFT_X, 26), "Claude Code + MusubiCAD plugin · real session, abridged", font=self.header, fill=COLORS["dim"])
        d.line((LEFT_X, 56, WIDTH - 30, 56), fill=(40, 49, 64), width=1)
        y = TOP
        for kind, text in lines:
            for row in wrap(text, 48):
                d.text((LEFT_X, y), row, font=self.mono, fill=COLORS[kind])
                y += 24
            y += 8
        x, py, w, h = PANEL
        if picture is not None:
            border = COLORS["bad"] if refused else (52, 63, 82)
            d.rounded_rectangle((x - 4, py - 4, x + w + 3, py + h + 3), radius=10, outline=border, width=4 if refused else 2)
            img.paste(picture, (x, py))
            if refused:
                badge = font(SANS_BOLD, 26)
                label = "✗  REFUSED · file unchanged"
                bw = d.textlength(label, font=badge) + 36
                bx, by = x + (w - bw) / 2, py + h - 70
                d.rounded_rectangle((bx, by, bx + bw, by + 46), radius=10, fill=(176, 38, 38))
                d.text((bx + 18, by + 8), label, font=badge, fill=(255, 255, 255))
            d.text((x, py + h + 16), caption, font=self.small, fill=COLORS["dim"])
        chip = font(SANS_BOLD, 17)
        cx = LEFT_X
        for i, label in enumerate(CHAPTERS):
            active = i == chapter
            tw = d.textlength(label, font=chip) + 32
            d.rounded_rectangle((cx, 612, cx + tw, 646), radius=17,
                                fill=(36, 99, 160) if active else (28, 35, 48),
                                outline=(109, 213, 255) if active else (52, 63, 82), width=2)
            d.text((cx + 16, 619), label, font=chip, fill=(255, 255, 255) if active else COLORS["dim"])
            cx += tw + 14
        return img

    def add(self, img: Image.Image, ms: int) -> None:
        self.frames.append(img)
        self.durations.append(ms)


def end_card(canvas: Canvas) -> Image.Image:
    img = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
    d = ImageDraw.Draw(img)
    mark = Image.open(MARK).convert("RGBA").resize((120, 120), Image.LANCZOS)
    img.paste(mark, ((WIDTH - 120) // 2, 120), mark)
    title = font(SANS_BOLD, 40)
    line = "Let your agent iterate on real CAD"
    d.text(((WIDTH - d.textlength(line, font=title)) / 2, 270), line, font=title, fill=COLORS["text"])
    sub = font(SANS_BOLD, 30)
    line = "every change verified"
    d.text(((WIDTH - d.textlength(line, font=sub)) / 2, 326), line, font=sub, fill=COLORS["ok"])
    formats = font(SANS, 22)
    line = "STEP · 3MF · STL · GLB · SVG · URDF"
    d.text(((WIDTH - d.textlength(line, font=formats)) / 2, 400), line, font=formats, fill=COLORS["tool"])
    mono = font(MONO, 18)
    line = "github.com/rsasaki0109/MusubiCAD"
    d.text(((WIDTH - d.textlength(line, font=mono)) / 2, 470), line, font=mono, fill=COLORS["user"])
    return img


def render(hub: list[Image.Image], arm: list[Image.Image]) -> Canvas:
    canvas = Canvas()
    box = shared_crop(hub)
    zoomed = [fit(image, box) for image in hub]
    holds = {"user": 1100, "tool": 450, "ok": 750, "bad": 1400, "text": 1300}
    for chapter, scene in enumerate(SCENES):
        shown: list[tuple[str, str]] = []
        picture, caption, refused = None, "", False
        for index, (kind, text, _, cue) in enumerate(scene):
            shown.append((kind, text))
            last = index == len(scene) - 1
            if cue == "morph":
                for step in zoomed[1:-1]:
                    canvas.add(canvas.base(shown, step, CAPTIONS["morph"], False, chapter), 120)
                picture, caption = zoomed[-1], CAPTIONS["morph"]
            elif cue == "arm":
                half = len(arm) // 2
                for frame in arm[:half]:
                    canvas.add(canvas.base(shown, fit(frame), CAPTIONS["arm"], False, chapter), 70)
                arm = arm[half:] + arm[:half]
                picture, caption = fit(arm[0]), CAPTIONS["arm"]
                continue
            elif cue == "start":
                picture, caption = zoomed[0], CAPTIONS["start"]
            elif cue == "agent":
                picture, caption = zoomed[-1], CAPTIONS["agent"]
            elif cue == "refused":
                refused, caption = True, CAPTIONS["refused"]
            if chapter == len(SCENES) - 1 and last:
                for frame in arm:
                    canvas.add(canvas.base(shown, fit(frame), CAPTIONS["arm"], False, chapter), 70)
                continue
            hold = holds[kind] + (700 if last else 0)
            canvas.add(canvas.base(shown, picture, caption, refused, chapter), hold)
    canvas.add(end_card(canvas), 2600)
    return canvas


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--musubicad", default="musubicad")
    parser.add_argument("--arm-gif", required=True, help="MuJoCo frames from render-urdf-mujoco.py")
    parser.add_argument("--output", default=str(OUTPUT))
    args = parser.parse_args()

    verify_facts(SESSION.read_text(encoding="utf-8"))
    arm = [f.convert("RGB") for f in ImageSequence.Iterator(Image.open(args.arm_gif))][::2]
    with tempfile.TemporaryDirectory() as tmp:
        hub = regenerate_hub_steps(shutil.which(args.musubicad) or args.musubicad, Path(tmp))
    canvas = render(hub, arm)
    frames = [f.quantize(colors=128, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE) for f in canvas.frames]
    frames[0].save(args.output, save_all=True, append_images=frames[1:], duration=canvas.durations, loop=0, optimize=True)
    print(f"{args.output}: {len(frames)} frames, {sum(canvas.durations) / 1000:.1f} s, {Path(args.output).stat().st_size / 1e6:.2f} MB")


if __name__ == "__main__":
    main()
